routes/web.php
<?php

use App\Http\Controllers\DataSetController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KoperasiController;
use App\Http\Controllers\LuasPerkebunanController;
use App\Http\Controllers\ResourceFileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('luas_perkebunan',LuasPerkebunanController::class);
Route::post('luas_perkebunan_satudata',[LuasPerkebunanController::class,'sendToSatuData'])->name('luas_perkebunan.satudata');
Route::resource('datasets',DataSetController::class);
Route::resource('resource_files',ResourceFileController::class);
Route::get('data_koperasi',[KoperasiController::class,'index'])->name('koperasi.index');
Route::post('koperasi_satudata',[KoperasiController::class,'sendToSatuData'])->name('koperasi.satudata');

app/Models/Dataset.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dataset extends Model
{
    use HasFactory;
    protected $table = 'dataset';
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    protected $fillable = [
        'package_id',
        'title',
        'owner_org',
        'language',
        'notes',
        'tahun',
        'cakupan'
    ];

    public function resourceFile()
    {
        return $this->hasMany(\App\Models\ResourceFile::class, 'dataset_id');
    }
}

app/Http/Controllers/DataSetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dataset;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class DataSetController extends Controller
{
    public function index()
    {
        $dataset = Dataset::all();
        return view('dataset.index',compact('dataset'));
    }

    public function create()
    {
        $dataset = new Dataset();
        return view('dataset.create',compact('dataset'));
    }

    public function store(Request $request)
    {
        $input = $request->all();
        $input['name'] = str_replace(' ', '-', strtolower($input['title']));
        $input['metadata_language'] = $input['language'];
        $input['owner_org'] = config('app.owner_org');
        $response = Http::withHeaders([
            'Authorization' => config('app.api_key_satudata'),
        ])->post('https://data.kutaitimurkab.go.id/api/3/action/package_create', $input);
        $input['package_id'] = $response['result']['id'];

        Dataset::create($input);

        return redirect(route('datasets.index'));
    }

    public function edit(Dataset $dataset)
    {
        return view('dataset.edit',compact('dataset'));
    }

    public function update(Request $request, Dataset $dataset)
    {
        $input = $request->all();
        $dataset->update($input);

        $input['id'] = $dataset->package_id;
        $input['name'] = str_replace(' ', '-', strtolower($input['title']));
        $input['metadata_language'] = $input['language'];
        $response = Http::withHeaders([
            'Authorization' => config('app.api_key_satudata'),
        ])->post('https://data.kutaitimurkab.go.id/api/3/action/package_update', $input);

        return redirect(route('datasets.index'));
    }

    public function destroy(Dataset $dataset)
    {
        $dataset->delete();
        $input['id'] = $dataset->package_id;
        $response = Http::withHeaders([
            'Authorization' => config('app.api_key_satudata'),
        ])->post('https://data.kutaitimurkab.go.id/api/3/action/package_delete', $input);

        return redirect(route('datasets.index'));
    }
}

resources/views/dataset/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 text-center">
                                    <i class="fa fa-edit fa-2x text-white text-center"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green h3">Input Dataset</span><br>
                                    <span style="margin-top: -5px">Membuat Dataset Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form" action="{{route('datasets.store')}}" method="POST">
                                    @csrf
                                    <div class="form-body">
                                        @include('dataset.fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/dataset/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo h3">Perubahan Dataset</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Dataset </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form action="{{route('datasets.update',$dataset->id)}}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-body">
                                        @include('dataset.fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/dataset/fields.blade.php
<div class="form-group">
    <label>Title/Judul Dataset:</label>
    <div class="position-relative">
        <input class="form-control" type="text" name="title" value="{{$dataset->title}}">
    </div>
</div>
<div class="form-group">
    <label>Bahasa:</label>
    <div class="position-relative">
        <input class="form-control" type="text" name="language" value="{{$dataset->language}}">
    </div>
</div>
<div class="form-group">
    <label>Cakupan:</label>
    <div class="position-relative">
        <input class="form-control" type="text" name="cakupan" value="{{$dataset->cakupan}}">
    </div>
</div>
<div class="form-group">
    <label>Tahun:</label>
    <div class="position-relative">
        <input class="form-control" type="number" name="tahun" value="{{$dataset->tahun}}">
    </div>
</div>
<div class="form-group">
    <label>Note/Keterangan:</label>
    <div class="position-relative">
        <textarea class="form-control" name="notes" rows="8">{{$dataset->notes}}</textarea>
    </div>
</div>
<div class="form-actions center">
    <a href="{!! route('datasets.index') !!}" class="btn btn-danger">Batal</a>
    <button type="submit" class="btn btn-success mr-1">Simpan</button>
</div>

resources/views/dataset/index.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="border-left-pink border-left-6 box-shadow-1 rounded">
                        <div class="card-content">
                            <div class="card-body card-dashboard">
                                <div class="row mb-2">
                                    <div class="col-10 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block h3"><b>Dataset</b></span>
                                        </div>
                                    </div>
                                    <div class="col-2 text-right">
                                        <a href="{!! route('datasets.create') !!}" class="btn btn-sm btn-outline-success">Tambah Data</a>
                                    </div>
                                </div>
                                @include('dataset.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dataset/table.blade.php
<table class="table table-hover table-bordered table-striped default">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Package id</th>
        <th>Title</th>
        <th>Organisasi id</th>
        <th>Bahasa</th>
        <th>Tahun</th>
        <th>Cakupan</th>
        <th>Keterangan</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($dataset as $item)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $item->package_id !!}</td>
            <td>{!! $item->title !!}</td>
            <td>{!! $item->owner_org !!}</td>
            <td>{!! $item->language !!}</td>
            <td>{!! $item->tahun !!}</td>
            <td>{!! $item->cakupan !!}</td>
            <td>{!! $item->notes !!}</td>
            <td class="text-center">
                <form action="{{route('datasets.destroy',$item->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{!! route('datasets.edit', [$item->id]) !!}" class="btn btn-sm btn-outline-warning"><i class="fa fa-edit"></i></a>
                        <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
                    </div>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>