routes/web.php
<?php

use App\Http\Controllers\DataSetController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KoperasiController;
use App\Http\Controllers\LuasPerkebunanController;
use App\Http\Controllers\ResourceFileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('luas_perkebunan',LuasPerkebunanController::class);
Route::post('luas_perkebunan_satudata',[LuasPerkebunanController::class,'sendToSatuData'])->name('luas_perkebunan.satudata');
Route::resource('datasets',DataSetController::class);
Route::resource('resource_files',ResourceFileController::class);
Route::get('data_koperasi',[KoperasiController::class,'index'])->name('koperasi.index');
Route::post('koperasi_satudata',[KoperasiController::class,'sendToSatuData'])->name('koperasi.satudata');

app/Models/ResourceFile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ResourceFile extends Model
{
    use HasFactory;
    protected $table = 'resource_file';
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    protected $fillable = [
        'file',
        'title',
        'description',
        'dataset_id',
        'resource_id',
    ];

    public function dataset()
    {
        return $this->belongsTo(\App\Models\Dataset::class, 'dataset_id');
    }
}

app/Http/Controllers/ResourceFileController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dataset;
use App\Models\ResourceFile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Schema;
use Mockery\Exception;

class ResourceFileController extends Controller
{
    public function index()
    {
        $resource_files = ResourceFile::all();
        $columns = Schema::getColumnListing('resource_file');
        $field = [];
        foreach ($columns as $column){
            array_push($field,['id'=>$column]);
        }
        return view('resource_file.index',compact('resource_files'));
    }

    public function create()
    {
        $resourceFile = new ResourceFile();
        $dataset = Dataset::all();
        return view('resource_file.create',compact('resourceFile','dataset'));
    }

    public function store(Request $request)
    {
        $input = $request->except('file');
        $dataset = Dataset::find($input['dataset_id']);
        $input['package_id'] = $dataset->package_id;
        $input['language'] = $dataset->language;
        $input['metadata_language'] = $dataset->language;
        $input['name'] = str_replace(' ', '-', strtolower($input['title']));
        $input['format'] = $request->file('file')->getClientOriginalExtension();
        try{
            DB::beginTransaction();
            $resource_file = ResourceFile::create($input);

            if( $request->hasFile('file')) {
                $response = Http::withHeaders(['Authorization' => config('app.api_key_satudata')])
                    ->attach('upload',fopen($request->file('file'),'r'),$input['title'].'.'.$request->file('file')->getClientOriginalExtension())
                    ->post('https://data.kutaitimurkab.go.id/api/3/action/resource_create', $input);
                $file = $request->file('file');
                $filenames = str_replace(" ", "_", $file->getClientOriginalName());
                $path=$request->file->storeAs('public/resource_file', $filenames,'local');
                $resource_file->file='storage'.substr($path,strpos($path,'/'));
                $resource_file->resource_id = $response['result']['id'];
                $resource_file->save();
                DB::commit();
            }
        }catch (Exception $e){
            DB::rollback();
        }
        return redirect(route('resource_files.index'));
    }

    public function edit(ResourceFile $resourceFile)
    {
        $dataset = Dataset::all();
        return view('resource_file.edit',compact('resourceFile','dataset'));
    }

    public function update(Request $request, ResourceFile $resourceFile)
    {
        $input = $request->except('file');
        try{
            DB::beginTransaction();
            $resourceFile->update($input);

            if( $request->hasFile('file')) {
                $response = Http::withHeaders(['Authorization' => config('app.api_key_satudata')])
                    ->attach('upload',fopen($request->file('file'),'r'),
                        $input['title'].'.'.$request->file('file')->getClientOriginalExtension())
                    ->post('https://data.kutaitimurkab.go.id/api/3/action/resource_update',
                        [
                            "id"=>$resourceFile->resource_id,
                            "name"=>str_replace(' ', '-', strtolower($input['title'])),
                            "format"=>$request->file('file')->getClientOriginalExtension()
                        ]);
                $file = $request->file('file');
                $filenames = str_replace(" ", "_", $file->getClientOriginalName());
                $path=$request->file->storeAs('public/resource_file', $filenames,'local');
                $resourceFile->file='storage'.substr($path,strpos($path,'/'));
                $resourceFile->save();

                DB::commit();
            }
        }catch (Exception $e){
            DB::rollback();
        }
        return redirect(route('resource_files.index'));
    }

    public function destroy(ResourceFile $resourceFile)
    {
        $resourceFile->delete();
        $input['id'] = $resourceFile->resource_id;
        $response = Http::withHeaders([
            'Authorization' => config('app.api_key_satudata'),
        ])->post('https://data.kutaitimurkab.go.id/api/3/action/resource_delete', $input);

        return redirect(route('resource_files.index'));
    }
}

resources/views/resource_file/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 text-center">
                                    <i class="fa fa-edit fa-2x text-white text-center"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green h3">Input Data Resource File</span><br>
                                    <span style="margin-top: -5px">Membuat Data Resource file baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form" action="{{route('resource_files.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-body">
                                        @include('resource_file.fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/resource_file/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo h3">Perubahan Data Resource</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Resource File </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form action="{{route('resource_files.update',$resourceFile->id)}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-body">
                                        @include('resource_file.fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/resource_file/fields.blade.php
<div class="form-group">
    <label>Title:</label>
    <div class="position-relative">
        <input class="form-control" type="text" name="title" value="{{$resourceFile->title}}">
    </div>
</div>
<div class="form-group">
    <label>Pilih Dataset:</label>
    <div class="position-relative">
        <select name="dataset_id" class="form-control">
            @foreach($dataset as $item)
                <option value="{{$item->id}}">{{$item->title}}</option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <label>File (XLS/CSV):</label>
    <div class="position-relative">
        <input class="form-control" type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, .csv, application/vnd.ms-excel" name="file"><span>{{$resourceFile->file}}</span>
    </div>
</div>
<div class="form-group">
    <label>Description:</label>
    <div class="position-relative">
        <textarea class="form-control" name="description" rows="8">{{$resourceFile->description}}</textarea>
    </div>
</div>
<div class="form-actions center">
    <a href="{!! route('resource_files.index') !!}" class="btn btn-danger">Batal</a>
    <button type="submit" class="btn btn-success mr-1">Simpan</button>
</div>

resources/views/resource_file/index.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="border-left-pink border-left-6 box-shadow-1 rounded">
                        <div class="card-content ">
                            <div class="card-body card-dashboard">
                                <div class="row mb-2">
                                    <div class="col-10 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block h3"><b>Data Resource File</b></span>
                                        </div>
                                    </div>
                                    <div class="col-2 text-right">
                                        <a href="{!! route('resource_files.create') !!}" class="btn btn-sm btn-outline-success">Tambah Data</a>
                                    </div>
                                </div>
                                @include('resource_file.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/resource_file/table.blade.php
<table class="table table-hover table-bordered table-striped default">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Resource id</th>
        <th>Title</th>
        <th>File</th>
        <th>Description</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($resource_files as $item)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $item->resource_id !!}</td>
            <td>{!! $item->title !!}</td>
            <td><a href="{!! $item->file !!}">{!! $item->file !!}</a></td>
            <td>{!! $item->description !!}</td>
            <td class="text-center">
                <form action="{{route('resource_files.destroy',$item->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{!! route('resource_files.edit', [$item->id]) !!}" class="btn btn-sm btn-outline-warning"><i class="fa fa-edit"></i></a>
                        <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
                    </div>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>