routes/web.php
<?php

use App\Http\Controllers\DataSetController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KoperasiController;
use App\Http\Controllers\LuasPerkebunanController;
use App\Http\Controllers\ResourceFileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('luas_perkebunan',LuasPerkebunanController::class);
Route::post('luas_perkebunan_satudata',[LuasPerkebunanController::class,'sendToSatuData'])->name('luas_perkebunan.satudata');
Route::resource('datasets',DataSetController::class);
Route::resource('resource_files',ResourceFileController::class);
Route::get('data_koperasi',[KoperasiController::class,'index'])->name('koperasi.index');
Route::post('koperasi_satudata',[KoperasiController::class,'sendToSatuData'])->name('koperasi.satudata');

app/Models/LuasPerkebunan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LuasPerkebunan extends Model
{
    use HasFactory;
    public $table = 'luas_perkebunan';
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    protected $fillable = [
        'kebun',
        'luas_lahan',
    ];
}

app/Http/Controllers/LuasPerkebunanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dataset;
use App\Models\LuasPerkebunan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Schema;
use Symfony\Component\VarDumper\Cloner\Data;

class LuasPerkebunanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataset = Dataset::all();
        $luas_perkebunan = LuasPerkebunan::all();
        return view('luas_perkebunan.index',compact('luas_perkebunan','dataset'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $luasPerkebunan = new LuasPerkebunan();
        return view('luas_perkebunan.create',compact('luasPerkebunan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        LuasPerkebunan::create($input);
        return redirect(route('luas_perkebunan.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\LuasPerkebunan  $luasPerkebunan
     * @return \Illuminate\Http\Response
     */
    public function show(LuasPerkebunan $luasPerkebunan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\LuasPerkebunan  $luasPerkebunan
     * @return \Illuminate\Http\Response
     */
    public function edit(LuasPerkebunan $luasPerkebunan)
    {
        return view('luas_perkebunan.edit',compact('luasPerkebunan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\LuasPerkebunan  $luasPerkebunan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, LuasPerkebunan $luasPerkebunan)
    {
        $input = $request->all();
        $luas_perkebunan = LuasPerkebunan::find($luasPerkebunan->id);
        $luas_perkebunan->update($input);
        return redirect(route('luas_perkebunan.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\LuasPerkebunan  $luasPerkebunan
     * @return \Illuminate\Http\Response
     */
    public function destroy(LuasPerkebunan $luasPerkebunan)
    {
        $luasPerkebunan->delete();

        return redirect(route('luas_perkebunan.index'));
    }

    public function sendToSatuData(Request $request){
        try{
            $package = Dataset::find($request->dataset_id);

            $resource['package_id'] = $package->package_id;
            $resource['language'] = $package->language;
            $resource['metadata_language'] = $package->language;
            $resource['name'] = 'Luas Perkebunan';
            $resource['title'] = 'Luas Perkebunan';
            $resource['description'] = 'Luas Perkebunan Kutim';
            $dataPerkebunan = LuasPerkebunan::all();
            foreach ($dataPerkebunan as $item){
                $item->luas_lahan = $item->luas_lahan.' Ha';
            }
            foreach ($dataPerkebunan as $item){
                unset($item['id']);
                unset($item['deleted_at']);
            }

            $columns = Schema::getColumnListing('luas_perkebunan');
            $field = [];
            foreach ($columns as $column){
                array_push($field,['id'=>$column]);
            }

            return $dataPerkebunan;

            $response = Http::withHeaders(['Authorization' => config('app.api_key_satudata')])
                ->post('https://data.kutaitimurkab.go.id/api/3/action/datastore_create',[
                    'resource' => $resource,
                    'fields' => $field,
                    'records' => $dataPerkebunan
                ]);
            return redirect(route('luas_perkebunan.index'))->with(['success'=>'Data berhasil di kirim']);
        }catch (\Exception $exception){
            return redirect(route('luas_perkebunan.index'),500)->with(['error'=>'Data gagal di kirim']);
        }
    }
}

resources/views/luas_perkebunan/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 text-center">
                                    <i class="fa fa-edit fa-2x text-white text-center"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green h3">Input Data Luas Perkebunan</span><br>
                                    <span style="margin-top: -5px">Membuat Data Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form" action="{{route('luas_perkebunan.store')}}" method="POST">
                                    @csrf
                                    <div class="form-body">
                                        @include('fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/luas_perkebunan/edit.blade.php
@extends('adminlte::page')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo h3">Perubahan Data Luas Perkebuan</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Luas Perkebunan </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form action="{{route('luas_perkebunan.update',$luasPerkebunan->id)}}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-body">
                                        @include('fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/luas_perkebunan/fields.blade.php
<!-- Nama Field -->
<div class="form-group">
    <label>Kebun:</label>
    <div class="position-relative">
        <input class="form-control" type="text" name="kebun" value="{{$luasPerkebunan->kebun}}">
    </div>
</div>


<!-- Pengertian Field -->
<div class="form-group">
    <label>Luas Lahan:</label>
    <div class="position-relative">
        <input class="form-control" type="text" name="luas_lahan" value="{{$luasPerkebunan->luas_lahan}}">
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Submit Field -->
<div class="form-actions center">
    <a href="{!! route('luas_perkebunan.index') !!}" class="btn btn-danger">Batal</a>
    <button type="submit" class="btn btn-success mr-1">Simpan</button>
</div>

resources/views/luas_perkebunan/index.blade.php
@extends('adminlte::page')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="border-left-green box-shadow-1 rounded">
                        <div class="card-content ">
                            <div class="card-body card-dashboard">
                                <div class="row mb-2">
                                    <div class="col-9 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block h3"><b>Data Luas Perkebunan</b></span>
                                        </div>
                                    </div>
                                    <div class="col-3 text-right">
                                        <a href="{!! route('luas_perkebunan.create') !!}" class="btn btn-sm btn-outline-success">Tambah Data</a>
                                    </div>
                                </div>
                                @if ($message = Session::get('success'))
                                    <div class="alert alert-default-success alert-block">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @endif
                                @if ($message = Session::get('error'))
                                    <div class="alert alert-danger alert-block">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <strong>{{ $message }}</strong>
                                    </div>
                                @endif

                                @include('table')
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card p-3">
                    <span class="h4"><b>Kirim ke Satu Data</b></span>
                    <form action="{{route('luas_perkebunan.satudata')}}" method="post">
                        @csrf
                        <div class="row m-2">
                            <label>Pilih Dataset:</label>
                            <div class="col-9">
                                <select name="dataset_id" class="form-control">
                                    @foreach($dataset as $item)
                                        <option value="{{$item->id}}">{{$item->title}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <span>
                            <button type="submit" class="btn btn-sm btn-outline-primary" onclick="return confirm('Apakah anda yakin untuk mengirim ke satu data?')">Kirim ke Satu Data</button>
                        </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/luas_perkebunan/table.blade.php
<!-- Sudah di modifikasi untuk Edit,Lihat,Hapus -->
<table class="table table-hover table-bordered table-striped default">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Kebun</th>
        <th>Luas Lahan</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($luas_perkebunan as $item)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $item->kebun !!}</td>
            <td>{!! $item->luas_lahan !!} Ha</td>
            <td class="text-center">
                <form action="{{route('luas_perkebunan.destroy',$item->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <div class="btn-group" role="group" aria-label="Basic example">
                        {{--<a href="{!! route('luas_perkebunan.show', [$item->id]) !!}" class="btn btn-sm btn-outline-success"><i class="fa fa-eye"></i></a>--}}
                        <a href="{!! route('luas_perkebunan.edit', [$item->id]) !!}" class="btn btn-sm btn-outline-warning"><i class="fa fa-edit"></i></a>
                        <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
                    </div>
                </form>

            </td>
        </tr>
    @endforeach
    </tbody>
</table>